# Generated by Django 6.0.2 on 2026-03-01 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_occurrence_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('discord', 'Discord'), ('slack', 'Slack'), ('mattermost', 'Mattermost')], max_length=50)),
                ('bot_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_integrations', to='api.organization')),
            ],
            options={
                'unique_together': {('organization', 'platform')},
            },
        ),
    ]
