[supervisord]
nodaemon=true

[program:discord_bot]
command=python bot.py
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/discord_bot.err.log
stdout_logfile=/var/log/supervisor/discord_bot.out.log
